<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260921122905 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE attribute_category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9ACE83315E237E06 ON attribute_category (name)');
        $this->addSql('CREATE TABLE attribute_definition (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, description VARCHAR(255) DEFAULT NULL, data_type VARCHAR(255) NOT NULL, version INT DEFAULT 1 NOT NULL, built_in BOOLEAN NOT NULL, category_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6C5628BD5E237E06 ON attribute_definition (name)');
        $this->addSql('CREATE INDEX IDX_6C5628BD12469DE2 ON attribute_definition (category_id)');
        $this->addSql('CREATE TABLE attribute_option (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, value VARCHAR(100) NOT NULL, definition_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_78672EEAD11EA911 ON attribute_option (definition_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_78672EEAD11EA9111D775834 ON attribute_option (definition_id, value)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, google_id VARCHAR(255) DEFAULT NULL, github_id VARCHAR(255) DEFAULT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D64976F5C865 ON "user" (google_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649D4327649 ON "user" (github_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('ALTER TABLE attribute_definition ADD CONSTRAINT FK_6C5628BD12469DE2 FOREIGN KEY (category_id) REFERENCES attribute_category (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE attribute_option ADD CONSTRAINT FK_78672EEAD11EA911 FOREIGN KEY (definition_id) REFERENCES attribute_definition (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql("
            INSERT INTO attribute_category (name) VALUES
            ('Personal'),
            ('Contact'),
            ('Education'),
            ('Work Experience'),
            ('Skills'),
            ('Languages'),
            ('Certifications'),
            ('Social & Links'),
            ('Preferences'),
            ('Other')
        ");
        $this->addSql("
            INSERT INTO attribute_definition
                (category_id, name, description, data_type, version, built_in)
            VALUES
                (
                    (SELECT id FROM attribute_category WHERE name = 'Personal'),
                    'First Name',
                    NULL,
                    'string',
                    1,
                    TRUE
                ),
                (
                    (SELECT id FROM attribute_category WHERE name = 'Personal'),
                    'Last Name',
                    NULL,
                    'string',
                    1,
                    TRUE
                ),
                (
                    (SELECT id FROM attribute_category WHERE name = 'Personal'),
                    'Personal Photo',
                    NULL,
                    'image',
                    1,
                    TRUE
                ),
                (
                    (SELECT id FROM attribute_category WHERE name = 'Personal'),
                    'Location',
                    NULL,
                    'string',
                    1,
                    TRUE
                )
        ");
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE attribute_definition DROP CONSTRAINT FK_6C5628BD12469DE2');
        $this->addSql('ALTER TABLE attribute_option DROP CONSTRAINT FK_78672EEAD11EA911');
        $this->addSql('DROP TABLE attribute_category');
        $this->addSql('DROP TABLE attribute_definition');
        $this->addSql('DROP TABLE attribute_option');
        $this->addSql('DROP TABLE "user"');
    }
}
